name: fooddelieveryapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.8.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  random_string: ^2.3.1
  shared_preferences: ^2.3.3
  firebase_storage: ^12.3.6
  cloudinary: ^1.2.0
  cloudinary_public: ^0.23.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
  assets:
    - images/
